name: Qullamaggie
gate:
  proxy: QQQ
  ema_short: 10
  ema_long: 20
  rising_lookback: 3
scan:
  adr_min_pct: 5
  rs_top_percentile: 0.90
setups:
  breakout:
    impulse_min_pct: 30
    lookback_impulse_days: 60
    flag_min_days: 5
    flag_max_days: 40
    atr_contract_ratio: 0.7
  ep:
    gap_min_pct: 10
    premkt_notional_min: 2000000
    require_big_volume_minutes: 10
    prefer_flat_prior_months: true
  parabolic_long:
    crash_min_pct: 50
    lookback_days: 7
    oversold_atr_multiple: 2.0
entry:
  or_minutes: 5
outputs:
  dir: artifacts
  save: true
tz: America/New_York
universe:
  mode: dynamic
  static_symbols:
    - NVDA
    - TSLA
    - COIN
    - AMD
    - ENPH
  min_price: 10.0
  min_avg_volume: 100000
  require_options: true
  exchanges:
    - NYSE
    - NASDAQ
