#!/usr/bin/env python3
"""
Email Output Generator for Filtered Stocks
"""
import os
from datetime import datetime

def generate_email_content():
    """Generate email content for filtered stocks"""
    
    # Filtered stocks data
    filtered_stocks = [
        {
            'symbol': 'INTC',
            'price': 37.01,
            'adr': 5.6,
            'rs': 9.25,
            'volume': 141165870,
            'sector': 'Semiconductors'
        },
        {
            'symbol': 'PTON',
            'price': 7.50,
            'adr': 6.8,
            'rs': 4.53,
            'volume': 15292861,
            'sector': 'Consumer Discretionary'
        },
        {
            'symbol': 'WDC',
            'price': 126.20,
            'adr': 5.4,
            'rs': 11.31,
            'volume': 10190818,
            'sector': 'Technology'
        },
        {
            'symbol': 'SEDG',
            'price': 37.02,
            'adr': 8.0,
            'rs': 5.99,
            'volume': 3518864,
            'sector': 'Energy'
        }
    ]
    
    # Generate email content
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    
    subject = f"🚀 BREAKOUT ALERT: {len(filtered_stocks)} High-Quality Stocks Found"
    
    body = f"""
📊 ADVANCED STOCK SCANNER RESULTS
================================
Scan Date: {timestamp}
Total Stocks Analyzed: 493
Stocks Passing Filters: {len(filtered_stocks)}
Success Rate: {len(filtered_stocks)/493*100:.1f}%

🎯 FILTERED STOCKS (All Criteria Met):
=====================================

"""
    
    for i, stock in enumerate(filtered_stocks, 1):
        body += f"""
{i}. ${stock['symbol']} - {stock['sector']}
   💰 Price: ${stock['price']:.2f}
   📈 ADR: {stock['adr']:.1f}% (✅ >5% required)
   🚀 RS: {stock['rs']:.2f} (✅ >1.0 required)
   📊 Volume: {stock['volume']:,} (✅ >500K required)
   ✅ All filters passed: Price, Volume, ADR, Relative Strength
"""
    
    body += f"""

📋 FILTER CRITERIA APPLIED:
==========================
✅ Price > $5 (avoid penny stocks)
✅ Avg Volume > 500,000 (liquidity)
✅ ADR > 5% (must move fast)
✅ Relative Strength > 1.0 (outperforming market)
✅ Market Cap > $300M (tradable size)

🎯 NEXT STEPS:
=============
1. Review technical charts for entry points
2. Set stop losses based on recent lows
3. Consider position sizing based on volatility
4. Monitor for volume confirmation on breakouts

⚠️  RISK DISCLAIMER:
===================
This is for informational purposes only. 
Past performance does not guarantee future results.
Always do your own research before trading.

---
Generated by Advanced Stock Scanner
Filter Success Rate: {len(filtered_stocks)/493*100:.1f}%
"""
    
    return subject, body

def main():
    """Generate and display email content"""
    subject, body = generate_email_content()
    
    print("📧 EMAIL CONTENT GENERATED")
    print("=" * 50)
    print(f"SUBJECT: {subject}")
    print("\nBODY:")
    print(body)
    
    # Save to file for email sending
    with open('/Users/deniz/Code/asymmetric/analyst/breakout/email_content.txt', 'w') as f:
        f.write(f"Subject: {subject}\n\n{body}")
    
    print(f"\n💾 Email content saved to: email_content.txt")

if __name__ == "__main__":
    main()
